/**
 * Cursed Contraptions — Centralized Configuration
 *
 * Gameplay values live here so every device follows the same, auditable rules.
 */

export const CONFIG = {
  namespace: "cc",

  debug: {
    enabled: false,
    chatDebug: false,
  },

  performance: {
    pollIntervalTicks: 5,
    idlePollIntervalTicks: 20,
    redstonePollIntervalTicks: 10,
    interactionFeedbackCooldownTicks: 40,
    maxActiveDevices: 32,
    entityScanRadius: 8,
    maxParticlesPerEvent: 8,
    chunkLoadGracePeriod: 40,
  },

  timings: {
    closedPauseTicks: 10,
    releaseAnimationTicks: 20,
    brokenAnimationTicks: 30,
  },

  ironMaiden: {
    captureRadius: 1.5,
    captureDelay: 20,
    closeDuration: 30,
    tortureInterval: 60,
    tortureMinDamage: 10,
    tortureMaxDamage: 18,
    extremeDamageChance: 0.05,
    extremeDamageAmount: 20,
    healAmount: 6,
    weaknessAmplifier: 0,
    weaknessDuration: 100,
    baseDurability: 200,
    armorSlots: 4,
    armorDurabilityBonus: 50,
    armorDamageMultiplier: 1.15,
    armorSpeedMultiplier: 0.9,
    redstoneActivationDelay: 10,
    dropOnBreak: true,
  },

  cursedStocks: {
    captureRadius: 1.2,
    captureDelay: 15,
    closeDuration: 20,
    tortureInterval: 80,
    tortureMinDamage: 4,
    tortureMaxDamage: 8,
    extremeDamageChance: 0.03,
    extremeDamageAmount: 12,
    healAmount: 3,
    weaknessAmplifier: 1,
    weaknessDuration: 120,
    baseDurability: 150,
    armorSlots: 2,
    armorDurabilityBonus: 30,
    armorDamageMultiplier: 1.1,
    armorSpeedMultiplier: 0.95,
    redstoneActivationDelay: 10,
    dropOnBreak: true,
  },

  gravebinderCage: {
    captureRadius: 1.8,
    captureDelay: 25,
    closeDuration: 35,
    tortureInterval: 50,
    tortureMinDamage: 6,
    tortureMaxDamage: 14,
    extremeDamageChance: 0.08,
    extremeDamageAmount: 16,
    healAmount: 4,
    weaknessAmplifier: 0,
    weaknessDuration: 80,
    baseDurability: 180,
    armorSlots: 3,
    armorDurabilityBonus: 40,
    armorDamageMultiplier: 1.12,
    armorSpeedMultiplier: 0.92,
    redstoneActivationDelay: 10,
    dropOnBreak: true,
  },

  regretRack: {
    captureRadius: 1.4,
    captureDelay: 30,
    closeDuration: 40,
    tortureInterval: 100,
    tortureMinDamage: 8,
    tortureMaxDamage: 16,
    extremeDamageChance: 0.04,
    extremeDamageAmount: 18,
    healAmount: 5,
    weaknessAmplifier: 0,
    weaknessDuration: 100,
    baseDurability: 300,
    armorSlots: 4,
    armorDurabilityBonus: 60,
    armorDamageMultiplier: 1.1,
    armorSpeedMultiplier: 0.95,
    redstoneActivationDelay: 15,
    dropOnBreak: true,
  },

  blackReliquary: {
    captureRadius: 2.0,
    captureDelay: 35,
    closeDuration: 45,
    tortureInterval: 40,
    tortureMinDamage: 12,
    tortureMaxDamage: 20,
    extremeDamageChance: 0.1,
    extremeDamageAmount: 24,
    healAmount: 8,
    weaknessAmplifier: 1,
    weaknessDuration: 60,
    baseDurability: 250,
    armorSlots: 4,
    armorDurabilityBonus: 50,
    armorDamageMultiplier: 1.2,
    armorSpeedMultiplier: 0.85,
    redstoneActivationDelay: 5,
    dropOnBreak: true,
  },

  vignette: {
    enabled: true,
    fadeInTicks: 10,
  },

  particles: {
    impactEnabled: true,
    smokeCount: 4,
    sparkEnabled: true,
    sparkCount: 2,
  },
};
